In [31]:
import numpy as np

In [52]:
 a = np.zeros((10,3))
a
y = np.array([0, 1, 2])

In [53]:
a[np.arange(10), y ] =1
a

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (10,) (3,) 

In [38]:
b = np.max(a, axis=1, keepdims=True)
b = np.ones((10,1))
b

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [37]:
a - b

array([[-1., -1.,  0.],
       [-1., -1.,  0.],
       [-1., -1.,  0.],
       [-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])

In [39]:
c = np.exp(a-b)

In [40]:
c


array([[0.36787944, 0.36787944, 1.        ],
       [0.36787944, 0.36787944, 1.        ],
       [0.36787944, 0.36787944, 1.        ],
       [0.36787944, 0.36787944, 0.36787944],
       [0.36787944, 0.36787944, 0.36787944],
       [0.36787944, 0.36787944, 0.36787944],
       [0.36787944, 0.36787944, 0.36787944],
       [0.36787944, 0.36787944, 0.36787944],
       [0.36787944, 0.36787944, 0.36787944],
       [0.36787944, 0.36787944, 0.36787944]])